-- Criação da tabela de histórico de arquivos
-- Execute este script no SQL Editor do seu projeto Supabase

CREATE TABLE IF NOT EXISTS historico_arquivos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Dados da Empresa (Cópia textual para persistir após exclusão da empresa original)
  empresa_nome TEXT NOT NULL,
  empresa_cnpj TEXT,
  
  -- Hierarquia
  tipo_empresa TEXT DEFAULT 'principal', -- 'principal' ou 'filial'
  nome_grupo TEXT, -- Se for filial, aqui vai o nome da Matriz. Se for matriz, repete o nome dela.
  
  -- Dados do Documento
  tipo_documento TEXT NOT NULL, -- 'PCMSO', 'LTCAT', 'PGR'
  ano_referencia TEXT,
  nome_arquivo TEXT NOT NULL,
  url_arquivo TEXT NOT NULL,
  
  -- Metadados
  data_upload TIMESTAMPTZ DEFAULT NOW(),
  usuario_responsavel TEXT -- Opcional, email do usuário que fez o upload
);

-- Habilitar RLS (Row Level Security) é recomendado
ALTER TABLE historico_arquivos ENABLE ROW LEVEL SECURITY;

-- Política de leitura: Todos podem ler (ou ajuste conforme necessidade)
CREATE POLICY "Leitura pública de histórico" 
ON historico_arquivos FOR SELECT 
USING (true);

-- Política de inserção: Autenticados podem inserir
CREATE POLICY "Inserção autenticada em histórico" 
ON historico_arquivos FOR INSERT 
WITH CHECK (auth.role() = 'authenticated');
